### ISSUE TITLE
proxy saves external image in a different folder instead of embedding them inside the result

### ISSUE THREAD

**Issue by silooz** [brcontainer/html2canvas-php-proxy#12]
here is code snippet

function screenShot(oElement) {
var html2obj = html2canvas(oElement,{logging: true, proxy:' html2canvasproxy.php'});
var queue = html2obj.parse();
var canvas = html2obj.render(queue);
var img = canvas.toDataURL();
return img;
}

screenShot($('#newDiv'));

**Comment by brcontainer** [comment]
html2canvas-0.4 create 2 requests:

1. Download image and send url for front-end
2. html2canvas get url and load

This url can be `Data URI Scheme` or `HTTP URI Scheme`.

In html2canvas-0.5 software is "changed", can work in two different ways:
1. Like in version 0.4.*
2. Auto-load image

If you used html2canvas-0.5 related: https://github.com/brcontainer/html2canvas-php-proxy/issues/11
If no, explain me better what happens.

**Comment by silooz** [comment]
I am using version 0.4.1 but  I have also tried version 0.5 with no change.
The problem is that I get errors from html2canvas  when it encounter  remote (not in same origin) images: 
html2canvas: Error loading <img>: URL
while i have set the proxy , and still get those errors.
The proxy save the external images in local folder ...but this is not helpful cause it is being done after the screenshot has already been created by HTML2Canvas.

So either i missed something here or it does not work as expected.
what to you mean by Auto-load image ? how do i set this option ? 
Do you mean that html2canvas will automatically take the remote images and insert them to the screenshot result ?

**Comment by brcontainer** [comment]
could provide the log in a more organized way? I can not understand what your log is returning. Would have an online example of the problem?

**Comment by silooz** [comment]
Hi , thank you for your help.
I did use the web console to diagnose the problem and i saw that when rendering 
html2canvas could not load remote image although i have tried using proxy in both versions.

I have created a jsfiddle with my code of both versions that I tried:


using version 0.4.1
https://jsfiddle.net/silooz/bes05g52/4/



using version 0.5
https://jsfiddle.net/silooz/exn75La8/2/

**Comment by brcontainer** [comment]
@silooz In your test, I noticed that you use the method "sync", try using callback (asynchronous).

> Note: Don't use `useCORS: true` (or allow taint) in same time when `proxy: ...`

Your code:
```js
var html2obj = html2canvas(oElement,{logging: true , proxy: sProxy });
var queue  = html2obj.parse();
var canvas = html2obj.render(queue);
var img = canvas.toDataURL();
```

Use like this https://github.com/brcontainer/html2canvas-php-proxy#usage :

```js
html2canvas(oElement, {
    "logging": true,
    "proxy": sProxy,
    "onrendered": function(canvas) {
        var img = canvas.toDataURL();
        document.body.appendChild(img);
    }
});
```

Online example: https://jsfiddle.net/bes05g52/5/

**Comment by silooz** [comment]
Man you are awesome!
you saved me a lot of headache with this issue , finally it works!
thank you.
