### ISSUE TITLE
Not getting data back but the path to the files (html2canvas 4.1)

### ISSUE THREAD

**Issue by slopespotter** [brcontainer/html2canvas-php-proxy#14]
Hello Guilherme,
I am trying your proxy with the CDN 4.1 version of html2canvas to fetch a whole site with images. The file fetching (html and images) works fine, everything is saved in the /images folder. However, upon returning to the script instead of getting the HTML and base64 encoded images, I receive the PATHs to the temp files. Thus the following standard implementation of html2canvas doesn't seem to work:

function startCapture2() {
  var url = "http://google.com";
  var urlParts = document.createElement('a');
  urlParts.href = url;  
  alert(urlParts.href); 
  
  $.getJSON("html2canvasproxy.php?callback=?", { xhr2:false, url:urlParts.href }, function(html) {
      alert(html);
      // NO HTML COMING BACK HERE BUT THE PATH http://localhost.......html

      iframe = document.createElement('iframe');
      $(iframe).css({ 'visibility':'hidden'}).width($(window).width()).height($(window).height());
      $('#content').append(iframe);
      d = iframe.contentWindow.document;
      d.open();
      $(iframe.contentWindow).load(iframeLoad.bind(null, iframe));
      $('base').attr('href',urlParts.protocol+"//"+urlParts.hostname+"/" + urlParts.pathname);
      html = html.replace("<head>","<head><base href='"+urlParts.protocol+"//"+urlParts.hostname+"/" + urlParts.pathname + "'  />");
      if($("#disablejs").prop('checked')){
        html = html.replace(/\<script/gi,"");
      }
      d.write(html);
      d.close();
  });
}

What am I missing here?
Thanks

**Comment by brcontainer** [comment]
html2canvas-php-proxy requires a "callback" valid (`?` is invalid) and this lib don't return json data, try this:

```
function createFrame(html) {
    console.log("createFrame:", html);

    var iframe = document.createElement('iframe');
    $(iframe).css({ 'visibility':'hidden'}).width($(window).width()).height($(window).height());
    $('#content').append(iframe);

    var d = iframe.contentWindow.document;
    d.open();

    $(iframe.contentWindow).load(iframeLoad.bind(null, iframe));

    $('base').attr('href', urlParts.protocol+"//"+urlParts.hostname+"/" + urlParts.pathname);
    html = html.replace("<head>", "<head><base href='"+urlParts.protocol+"//"+urlParts.hostname + "/" + urlParts.pathname + "'  />");

    if($("#disablejs").prop('checked')){
        html = html.replace(/\<script/gi,"<!--<script");
        html = html.replace(/\<\/script\>/gi,"<\/script>-->");
    }

    d.write(html);
    d.close();
}

function startCapture2() {
    var url = "http://google.com";
    var urlParts = document.createElement('a');
    urlParts.href = url;

    console.log("URL:", urlParts.href);

    $.ajax("example.php", {
        "data": {
            "url": urlParts.href,
            "callback": "createFrame"
        }
    }).done(function(response) {
        if (response.indexOf("createFrame(") === 0) {
            window.setTimeout(response, 1);
        } else {
            console.log("error:", response);
        }
    }).fail(function(err) {
        console.log("error:", err);
    });
}
```

**Comment by slopespotter** [comment]
Thanks for getting back with me!
The callback seems to work, but the console output after createFrame still shows the URL and not the HTML content.
![html2canvasproxy-firebug-output-0](https://cloud.githubusercontent.com/assets/12134164/7351998/237a3564-ed09-11e4-8b24-02fafc7f782c.png)

**Comment by brcontainer** [comment]
@slopespotter Firebug is confuse for me, show me the error in Chrome Console.

**Comment by slopespotter** [comment]
Of course.
![html2canvasproxy-chrome-output-0](https://cloud.githubusercontent.com/assets/12134164/7530089/e1a15f5e-f542-11e4-98f6-84ea0cb8c6be.png)

**Comment by brcontainer** [comment]
jQuery trying detect response type, but in your code is needed textplain, try this:

```
        $.ajax("html2canvasproxy.php", {
            "dataType": "text", //Fix response type
            "data": {
                "url": urlParts.href,
                "callback": "createFrame"
            }
        }).done(function(response) {
            if (response.indexOf("createFrame(") === 0) {
                window.setTimeout(response, 1);
            } else {
                console.log("error:", response);
            }
        }).fail(function(err) {
            console.log("error:", err);
        });
```
