### ISSUE TITLE
Uncaught ReferenceError: html2canvas_X is not defined

### ISSUE THREAD

**Issue by brds85** [brcontainer/html2canvas-php-proxy#15]
I have three different divs that i'm turning into images with id's of "boxBanner", "skyscraperBanner", and "scoreboxBanner".  When the user clicks a button, I'm running a function that does the following code for each of the three IDs:

html2canvas($("#[DIV ID HERE]"), {
        proxy: "./proxy.php",
        onrendered: function(canvas) {
        var theCanvas = canvas;
        $("#resultsArea").append(canvas);
        }
});

This code will only render one of the three images.  In the console, I get an error stating "Uncaught ReferenceError: html2canvas_0 is not defined" with a 2 next two it, (one for each of the divs that isn't the first i'm assuming).  

Is there a fix for this?

**Comment by brcontainer** [comment]
Sounds like bug in html2canvas and not in proxy, see this pullrequest: https://github.com/niklasvh/html2canvas/pull/554

Thanks!
