### ISSUE TITLE
Proxy loads images but doesn't fulfil promises in html2canvas

### ISSUE THREAD

**Issue by carolgilabert** [brcontainer/html2canvas-php-proxy#16]
Hi!

I'm trying to use this proxy to load cross origin images to my canvas. The images are downloaded correctly, but html2canvas says the image load failed. The promises are not being fulfilled correctly.

From the network requests to the proxy, I can see the response as a console.log with the image in base 64.

![image](https://cloud.githubusercontent.com/assets/10845908/9405859/4d00c264-47f3-11e5-9c5f-e92c1613962b.png)

Html2canvas, in turn, displays this:

![image](https://cloud.githubusercontent.com/assets/10845908/9405881/81877c58-47f3-11e5-8951-53dc6f011fc2.png)

Any help would be much appreciated, thanks!

**Comment by brcontainer** [comment]
@carolgilabert Put a example please, I tested here and apparently it works.

**Comment by brcontainer** [comment]
@carolgilabert Improved script for work in PHP5.6 on Windows, please try new version:

- Download https://github.com/brcontainer/html2canvas-php-proxy/archive/master.zip
- GIT: git@github.com:brcontainer/html2canvas-php-proxy.git

Update details:

https://github.com/brcontainer/html2canvas-php-proxy/commit/184342b9db5e8642ae51ec2d0d9670273b816068 https://github.com/brcontainer/html2canvas-php-proxy/commit/11d8cf5124e4be1d58f77020ef39849fe3ec72ca

**Comment by brcontainer** [comment]
@carolgilabert html2canvas 0.5 support added: https://github.com/brcontainer/html2canvas-php-proxy/commit/10dd9bd52f6d523ff05e3d2a6499c2743ec7ee5e
