### ISSUE TITLE
screenshot from external url

### ISSUE THREAD

**Issue by ucitelot** [brcontainer/html2canvas-php-proxy#17]
how can i get working like this
http://html2canvas.hertzen.com/screenshots.html

with external url of full website ?

**Comment by brcontainer** [comment]
Inject script html2canvas in your iframe and use absolute path to proxy:

```javascript
html2canvas(document.body, {
    "logging": true, //Enable log (use Web Console for get Errors and Warnings)
    "proxy":"http://mywebsite.com/html2canvasproxy.php"
}).done(function() {});
```

**Comment by ucitelot** [comment]
this return me 
http://localhost/html2canvas-php-proxy-master/html2canvasproxy.php?callback=CALLBACK_JAVASCRIPT&url=http://www.w3schools.com/html/html_iframe.asp

CALLBACK_JAVASCRIPT("http:\/\/localhost\/html2canvas-php-proxy-master\/images\/h2c_8cbbe60c9fa123d228c688b7088247ac5f70e1be
![iframe](https://cloud.githubusercontent.com/assets/182839/10375912/514eb118-6dfb-11e5-9dc2-f5fd718ba756.jpg)
.html");

how can i make like on the example with input field and to grab url from that field

can you help me with some code
thanks a lot

**Comment by ucitelot** [comment]
here is nise example of external url
byt i couldnt make it working with html2canvasproxy.php
http://jsfiddle.net/RbY4E/

**Comment by brcontainer** [comment]
@ucitelot Improved script for work in PHP5.6 on Windows, please try new version:

- Download https://github.com/brcontainer/html2canvas-php-proxy/archive/master.zip
- GIT: `git@github.com:brcontainer/html2canvas-php-proxy.git`

Update details:

https://github.com/brcontainer/html2canvas-php-proxy/commit/184342b9db5e8642ae51ec2d0d9670273b816068 https://github.com/brcontainer/html2canvas-php-proxy/commit/11d8cf5124e4be1d58f77020ef39849fe3ec72ca
