### ISSUE TITLE
The execution time is not configured enough to TIMEOUT in SOCKET

### ISSUE THREAD

**Issue by C4rter** [brcontainer/html2canvas-php-proxy#19]
I set up your proxy solution with html2canvas two weeks ago. Everything was working fine. Images were downloaded and displayed.

Now I wanted to work some more with it but suddenly it stopped working.
To make sure I didn't broke anything I tried to get your example running but the example also isn't working somehow. Every image fails to be downloaded.

Can you please have a look here?
http://www.moviegeek.de/test.html

**Comment by C4rter** [comment]
In my local environment in my actual project, another error is thrown in the Firebug console:
NetworkError: 404 Not Found - https://localhost/print-div/images/h2c_d4bd2825638c24251e6938b907b744ace2fb55e6.png
That's happening for every image.

**Comment by C4rter** [comment]
I think I found out that some PHP setting might have changed on my local environment and that's why it's not working anymore.

What I don't understand is, why the image name is communicated to html2canvas but the image isn't save on the server by the proxy script anymore.

**Comment by brcontainer** [comment]
@C4rter  try html2canvas 0.5

**Comment by C4rter** [comment]
@brcontainer Thanks for the tip. Now the proxy script is working again and is saving all the images.
But the html2canvas script is reporting this in Firebug and therefore the images are still "grey" instead of the actual image:

647ms html2canvas: Failed loading image #1 ProxyImageContainer { src="http://maps.gstatic.com/...pi-3/images/google4.png",  image=img,  promise=Promise} error 
html2canvas.js (Zeile 1487)
647ms html2canvas: DummyImageContainer for http://maps.gstatic.com/mapfiles/api-3/images/google4.png

**Comment by brcontainer** [comment]
@C4rter I see, I will try

**Comment by C4rter** [comment]
Great, thank you.

**Comment by brcontainer** [comment]
@C4rter See error log:

> error: html2canvas-proxy-php: The execution time is not configured enough to TIMEOUT in SOCKET, configure this with ini_set/set_time_limit or "php.ini" (if safe_mode is enabled), recommended that the "max_execution_time =;" be a minimum of 5 seconds longer or reduce the TIMEOUT in "define('TIMEOUT', 30);"

It's error in your configs, increase time in `max_execution_time =;` (php.ini or php_module) or use `set_time_limit` in `html2canvasproxy.php`, see:

```php
<?php
/*
 * html2canvas-php-proxy 0.1.11
 * Copyright (c) 2014 Guilherme Nascimento (brcontainer@yahoo.com.br)
 * 
 * Released under the MIT license
 */
set_time_limit(0);

//Turn off errors because the script already own uses "error_get_last"
error_reporting(0);
//setup
define('JSLOG', 'console.log'); //Configure alternative function log, eg. console.log, alert, custom_function
define('PATH', 'images');//relative folder where the images are saved
define('CCACHE', 60 * 5 * 1000);//Limit access-control and cache, define 0/false/null/-1 to not use "http header cache"
define('TIMEOUT', 30);//Timeout from load Socket
define('MAX_LOOP', 10);//Configure loop limit for redirect (location header)
define('CROSS_DOMAIN', 0);//Enable use of "data URI scheme"
```

**Comment by C4rter** [comment]
@brcontainer Sorry, I already fixed this time limit issue in my local environment but not on the server I showed you. I added your line "set_time_limit(0);" but now I get another error:

console.log("error: html2canvas-proxy-php: Execution time is less 15 seconds, configure this with ini_set\/set_time_limit or \"php.ini\" (if safe_mode is enabled), recommended time is 30 seconds or more");

I think that's thrown because of the condition "} else if(MAX_EXEC < 10) {".
I've changed it to "set_time_limit(60);" instead.

If you have another look at it now it shows the same problem I have on my local environment:
http://www.moviegeek.de/test.html

**Comment by C4rter** [comment]
@brcontainer I've read some other issues and I guess with the update to html2canvas 0.5 I've got this issue now?
https://github.com/brcontainer/html2canvas-php-proxy/issues/11

**Comment by C4rter** [comment]
@brcontainer I've tried something else and switched back to html2canvas 0.4.1 on my local environment and I noticed something strange:

With 0.5 the images are only downloaded via the proxy but not used by html2canvas.
With 0.4.1, the images are not correctly downloaded anymore.
But, when the images are already downloaded (via the 0.5 version) they are used by the 0.4.1 version to print.

**Comment by C4rter** [comment]
@brcontainer I've created another example from scratch. What I noticed was, that the first try worked flawlessly today. Afterwards I've deleted all the images from the images folder. Afterwards, it failed.

You can see the example here:
http://www.moviegeek.de/test3.html

**Comment by C4rter** [comment]
I think I found out something important. It seems that Firefox and Chrome are trying to load the callbacks to the proxy file from cache. But if the image isn't available anymore on the server, this fails, and therefore resulting in the grey image.

**Comment by C4rter** [comment]
@brcontainer I've noticed the "CCACHE" setting in the proxy file and configured it to "false".
I've deleted all the browser caches and tried again. It seems to work now. But I'll need to check further.

Can you describe how the cache works? I'm not allowed to remove images the proxy creates, correct? The proxy itself takes care of this?

Maybe we should rename the topic again. :-)

**Comment by brcontainer** [comment]
> The images are generated by the proxy and put into the "images" subfolder, but html2canvas isn't using them.

Subfolder is `images/`? Folder exists? Is writable?

> I think that's thrown because of the condition "} else if(MAX_EXEC < 10) {".
I've changed it to "set_time_limit(60);" instead.

It's make sense, I will try send a update =)

**Comment by C4rter** [comment]
> Subfolder is images/? Folder exists? Is writable?

Yes the folder is available and writable.

At first the issue seemed to be the following:
The cache was active but the images were deleted (by me). That lead to this behavior:
- First try, images downloaded by proxy, everything was fine.
- Images now removed from /images folder.
- Second try, the cache is returning only the alleged image path. But the image is now missing (because of the removal).

Once I've set the cache to "false" everything seemed to be working.

But now, I've encountered another issue.
Even with the cache now set to inactive, the proxy seems to be returning the wrong images (and sometimes none at all) in this example:
http://www.moviegeek.de/test3.html

You can try it out.
Open the link, click "Save #container", scroll the map or zoom out, and click on "Save #container" again. It returns the same image instead of the new one.

**Comment by C4rter** [comment]
@brcontainer Sometimes it like some images can be loaded and saved and same can't. In these cases I get a map with some grey areas. The proxy still is returning the URL to the image, but the image isn't available via this url. That's so strange.

**Comment by brcontainer** [comment]
> Images now removed from /images folder.

The PHP script removes the images automatically, if removes manually causes errors.

I'm checking the script and running tests, as soon as possible I will come back with some solution.

Thanks for your effort.

**Comment by brcontainer** [comment]
@C4rter Improved script for work in PHP5.6 on Windows, please try new version:

- Download https://github.com/brcontainer/html2canvas-php-proxy/archive/master.zip
- GIT: git@github.com:brcontainer/html2canvas-php-proxy.git

Update details:

https://github.com/brcontainer/html2canvas-php-proxy/commit/184342b9db5e8642ae51ec2d0d9670273b816068 https://github.com/brcontainer/html2canvas-php-proxy/commit/11d8cf5124e4be1d58f77020ef39849fe3ec72ca
