### ISSUE TITLE
Does this still work..?

### ISSUE THREAD

**Issue by sparcut** [brcontainer/html2canvas-php-proxy#22]
Hey, I have been trying to get this working. But after uploading the example to my site, it doesn't work and pushes this to the console: 

![image](https://cloud.githubusercontent.com/assets/16233822/18246934/6cacb6f4-73b2-11e6-9c4d-3db6fdf5012b.png)

I had only tested this since it was not working with the code I had cooked up from the "usage" section in README.

Any idea how I can fix this? Or is this no longer being support?

Cheers.

**Comment by brcontainer** [comment]
@sparcut Yes work, the problem is with Google Maps that made things difficult, it takes the "KEY" to access them and also some other features, GoogleMaps is a bit tricky.

The problem is not about the proxy, but even though there will try to create an example of how to get around the problem.

**Comment by sparcut** [comment]
@brcontainer Sorry, was going through emails and must have missed this!

I understand what you are saying, though I am not only having a problem with GoogleMaps, rather, everything I have tried using this script with is not working - demos, examples ect.

Again, sorry for the (really) late response!

**Comment by brcontainer** [comment]
@sparcut I tried in PHP5.4 and work fine, but in PHP5.6 (x64) on Windows not work if URL is HTTPS. It's BUG in PHP for windows, but I'm not sure.

**Comment by brcontainer** [comment]
@sparcut I update script: https://github.com/brcontainer/html2canvas-php-proxy/commit/184342b9db5e8642ae51ec2d0d9670273b816068

try version 0.1.3: https://raw.githubusercontent.com/brcontainer/html2canvas-php-proxy/master/html2canvasproxy.php

**Comment by sparcut** [comment]
Hmm, I've tried with version 0.1.3 and now 0.2.0, the images still aren't showing up in rendered canvas, just the text. Your github profile picture, and github logo from facebook load into the page, but don't don't show in canvas render.

The google maps thing has never worked, not sure why, but I'm not to fussed over that.

I am running php 5.5 (just tried 5.4 with no luck or change) on a linux server with cPanel.

**Comment by brcontainer** [comment]
@sparcut in localhost work?

Tried you https://github.com/brcontainer/html2canvas-php-proxy/blob/master/examples/html2canvas-0.5.html example?

**Comment by sparcut** [comment]
Alright, tried running it locally, still not working :(

But, here's a screenshot of the console if it helps.

![Console](https://cloud.githubusercontent.com/assets/16233822/19132707/9a7a39c0-8ba0-11e6-89e8-5fa3f19df699.png)

**Comment by brcontainer** [comment]
@sparcut please run `<?php phpinfo();` copy source from page and paste in http://pastebin.com

**Comment by sparcut** [comment]
@brcontainer I have emailed _(privacy reasons)_ phpinfo() for both my local setup and Linux server.

**Comment by valpatsk** [comment]
Hello. I can see the same problem. I run php 5.4. Can you tell what was the problem ?
Thanks

**Comment by brcontainer** [comment]
@valpatsk google maps?

**Comment by valpatsk** [comment]
@brcontainer it was just a default call of html2canvas with proxy. Windows, Chrome. Any image on the page I was making the screenshot

**Comment by brcontainer** [comment]
@valpatsk can you provide an example? Thanks

**Comment by valpatsk** [comment]
@brcontainer I was makint the test with your html2canvas-0.5.html example page. 
I am sorry, it seem do not depend on firewall.
When "useCORS": false - it always fail to load images even from local server;
when "useCORS": true - it loads images from local server nicely and usually (not always) loads images from facebook etc. but sometimes fail too. I can't see the reason

It works in this way both for you example and my code

**Comment by brcontainer** [comment]
@valpatsk  check php log, sounds like a error with php extensions or try this https://github.com/brcontainer/html2canvas-php-proxy#using-web-console

**Comment by brcontainer** [comment]
@sparcut update examples: https://github.com/brcontainer/html2canvas-php-proxy/blob/master/examples/html2canvas-0.5.html and https://github.com/brcontainer/html2canvas-php-proxy/blob/master/examples/html2canvas-0.4.1.html

About errors: https://github.com/brcontainer/html2canvas-php-proxy#problems-and-solutions
