### ISSUE TITLE
It's not working...

### ISSUE THREAD

**Issue by rexchungrs24** [brcontainer/html2canvas-php-proxy#25]
Hello L,
I run your test case and it's not working, is it still working?

Also, actually what I want is that save the google adsense to png, is it possible?

**Comment by brcontainer** [comment]
@rexchungrs24 Please, provide details. You using with googlemaps?

**Comment by brcontainer** [comment]
@rexchungrs24 

- Common issues: https://github.com/brcontainer/html2canvas-php-proxy#problems-and-solutions
- How debug: https://github.com/brcontainer/html2canvas-php-proxy#using-web-console
