### ISSUE TITLE
Cannot create file

### ISSUE THREAD

**Issue by NJseo** [brcontainer/html2canvas-php-proxy#26]
error: html2canvas-proxy-php: Can not create file:

**Comment by NJseo** [comment]
Also, as a note, I am attempting to create and image from an iframe.

**Comment by brcontainer** [comment]
@NJseo folder permissions?

**Comment by NJseo** [comment]
I had to reset the folder permissions. That seemed to work for a remote image but not for the iframe

**Comment by brcontainer** [comment]
@NJseo Windows Server, Linux, Mac? PHP version? Details please.

**Comment by NJseo** [comment]
PHP version 7 Cloudways Linux

**Comment by brcontainer** [comment]
@NJseo in local machine it works?
