### ISSUE TITLE
Capture Screen seems to be broken. 

### ISSUE THREAD

**Issue by sathiyaraj45** [brcontainer/html2canvas-php-proxy#30]
Hi,

I have integrated google map in our project and this application I have used to image capture option with html2canvas feature. Use this package I have facing the following list of problems. 

1. Sometimes the image seem is broken.
2. We are using an iframe in the application and it is open and took the image capture means some error is showing. 

Failed to load https://github.com/brcontainer/html2canvas-php-proxy?url=about%3Ablank: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
html2canvas.js:1488 3745ms html2canvas: Failed loading image #19 FrameContainer {image: null, src: iframe, promise: Promise}image: Event {isTrusted: true, type: "load", target: null, currentTarget: null, eventPhase: 0, …}promise: Promise {<rejected>: Error: Network Error
    at XMLHttpRequest.xhr.onerror (http://localhost:3000/js/lib/html2canvas/htm…}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: Network Error
    at XMLHttpRequest.xhr.onerror (http://localhost:3000/js/lib/html2canvas/html2canvas.js:3193:20)src: iframe__proto__: Object Error: Network Error
    at XMLHttpRequest.xhr.onerror (html2canvas.js:3193)

**Comment by brcontainer** [comment]
@sathiyaraj45 load `about:blank` in proxy? It's sound like a error in your HTML document.

**Comment by brcontainer** [comment]
@sathiyaraj45  this url not make sense:

```
https://github.com/brcontainer/html2canvas-php-proxy
```
this is the url of the repository and not the proxy. Something wrong you did.

**Comment by sathiyaraj45** [comment]
@brcontainer Ok. I will change the proxy server URL and one thing I added in logging properties in conversion, It's showing the below error 

TypeError: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The provided value is not of type '(CSSImageValue or HTMLImageElement or SVGImageElement or HTMLVideoElement or HTMLCanvasElement or ImageBitmap or OffscreenCanvas)'
    at CanvasRenderer.drawImage (html2canvas.js:3261)
    at CanvasRenderer.Renderer.renderImage (html2canvas.js:2884)
    at NodeParser.<anonymous> (html2canvas.js:2229)
    at CanvasRenderer.clip (html2canvas.js:3270)
    at NodeParser.paintElement (html2canvas.js:2223)
    at NodeParser.paintNode (html2canvas.js:2209)
    at NodeParser.paint (html2canvas.js:2185)
    at NodeParser.asyncRenderer (html2canvas.js:1991)
    at NodeParser.asyncRenderer (html2canvas.js:1995)
    at NodeParser.asyncRenderer (html2canvas.js:1995)

**Comment by sathiyaraj45** [comment]
Here I have shared the image screen short of my capture image.
https://ibb.co/i22vQp

**Comment by brcontainer** [comment]
@sathiyaraj45 php proxy requires a php server, by your message you ins't use php server, try use:

- Xampp https://www.apachefriends.org/index.html
- Wamp http://www.wampserver.com/en/
- EasyPHP http://www.easyphp.org

Your issue **ins't a bug**, So please move similar problems to the stackoverflow:

- https://stackoverflow.com

**Comment by sathiyaraj45** [comment]
I have resolved the proxy server issue in my code even though still image is broke. 

Ref: https://ibb.co/i22vQp

**Comment by brcontainer** [comment]
@sathiyaraj45 see box error, is showed PHP like text, in HTTP servers configure with PHP, the source from PHP script are not showed in webbrowser.


if the php is appearing in the browser means that your server is not a php server, or your server is misconfigured, it is not a BUG, it is a problem in your settings or your understanding of PHP, please ask a question on stackoverflow. with details.

The "issues" is used to report BUGs, I can not give guidance on the basic use of HTTP and PHP scripts here.

I hope you understand. Thanks!
