### ISSUE TITLE
Port not allowed

### ISSUE THREAD

**Issue by ashleyCheuk12** [brcontainer/html2canvas-php-proxy#31]
Hey Guys,

Thanks for the port, i put the php script on to my websever when i call it i recieve ("error: html2canvas-proxy-php: \"443\" port is not allowed");

html2canvasproxy.php?url=https://www.roadrunnerrecords.com/sites/g/files/g2000005056/f/Sample-image10-highres.jpg 

i haven't changed any content from the script so allowed ports is still the same

define('H2CP_ALLOWED_PORTS', array( 80, 443 )); // Allowed ports

Are there any setup steps i need to do?

Thanks

**Comment by brcontainer** [comment]
@ashleyCheuk12 thanks by reporting this bug, I will correct it today.
