### ISSUE TITLE
Not running on client side

### ISSUE THREAD

**Issue by ademadam** [brcontainer/html2canvas-php-proxy#34]
Hey ,
Thanks for your great script , 
i wanted to make an iframe with the same origin policy pointed to another domain , but i've rad your README.md and you mentioned that you need proxy , but after this when i do the iframe , it running on the server side not on the client side ,
Every image called from the server side not on the client side ,
And thanks

**Comment by brcontainer** [comment]
@ademadam Thanks!

So, here I only deal with BUGs and improvements on the specific script for the use of html2canvas.

If you’re creating something yourself I recommend you ask at stackoverflow.com

If I understand your question, if you don't disregard what I said and explain the need better.
